"""Analyze registered Protocol-035 C_ref_035 vs D_corr without tuning."""
from __future__ import annotations
import argparse,json
from pathlib import Path
import numpy as np
from protocol035_common import dump_json,load_npz,binary_metrics,phase_bounds,WINDOWS,W_BLOCKS,pooled_ranges

def diff(d,c):
    return {k+'_delta':None if d[k] is None or c[k] is None else float(d[k]-c[k]) for k in ('ap','bce','recall','fpr')}
def block(p,y,a,b): return binary_metrics(p[a:b],y[a:b])
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--run-root',required=True); ap.add_argument('--stream-manifest',required=True); ap.add_argument('--diagnostic',required=True); ap.add_argument('--reference',required=True); ap.add_argument('--fixture',required=True); ap.add_argument('--output-dir',required=True); ap.add_argument('--docs-output',required=True); ap.add_argument('--run-id',required=True); a=ap.parse_args()
    root=Path(a.run_root); out=Path(a.output_dir); out.mkdir(parents=True,exist_ok=True); bounds=phase_bounds(a.stream_manifest); C=load_npz(root/'C_ref_035'/'predictions.npz'); D=load_npz(root/'D_corr_branch'/'predictions.npz'); O=load_npz(root/'D_off_exact_C_copy'/'predictions.npz'); y=C['labels']
    if not(np.array_equal(y,D['labels']) and np.array_equal(y,O['labels'])): raise AssertionError('label mismatch')
    d_off=all(np.array_equal(C[k],O[k]) for k in ('probability','class_probability','detection_logits','class_logits','labels','raw_labels')); cls=bool(np.array_equal(C['class_probability'],D['class_probability'])); fc=binary_metrics(C['probability'],y); fd=binary_metrics(D['probability'],y)
    wins=[]
    for n,s,e in WINDOWS:
        cm=block(C['probability'],y,s,e); dm=block(D['probability'],y,s,e); c32=block(C['probability'],y,s,s+32); d32=block(D['probability'],y,s,s+32); c64=block(C['probability'],y,s,s+64); d64=block(D['probability'],y,s,s+64)
        wins.append({'window':n,'intervals':[s,e],'C':cm,'D_corr':dm,**diff(dm,cm),'prefix32':{'C':c32,'D_corr':d32,**diff(d32,c32)},'prefix64':{'C':c64,'D_corr':d64,**diff(d64,c64)}})
    mean6=float(np.mean([w['ap_delta'] for w in wins])); pos=sum(w['ap_delta']>0 for w in wins); late=float(np.mean([w['ap_delta'] for w in wins if w['window'] in {'U_rec2','V_rec2','U_rec3','V_rec3'}])); first32=float(np.mean([w['prefix32']['ap_delta'] for w in wins])); first64=float(np.mean([w['prefix64']['ap_delta'] for w in wins])); pc=pooled_ranges(C['probability'],y,WINDOWS); pd=pooled_ranges(D['probability'],y,WINDOWS)
    wr=[]
    for n in W_BLOCKS:
        s,e=bounds[n]; cm=block(C['probability'],y,s,e); dm=block(D['probability'],y,s,e); wr.append({'phase':n,'C':cm,'D_corr':dm,**diff(dm,cm)})
    wmean=float(np.mean([x['ap_delta'] for x in wr])); full=float(fd['ap']-fc['ap']); online=bool(full>=.005 and mean6>=0 and late>=-.005); recurrence=bool(mean6>=.005 and pos>=4 and late>=0 and first32>=-.005 and full>=0)
    guards={'full_fpr_delta':float(fd['fpr']-fc['fpr']),'full_recall_delta':float(fd['recall']-fc['recall']),'recurrence_pooled_fpr_delta':float(pd['fpr']-pc['fpr']),'recurrence_pooled_recall_delta':float(pd['recall']-pc['recall']),'W_equal_weight_mean_AP_delta':wmean}; guards['all_pass']=bool(guards['full_fpr_delta']<=.01 and guards['recurrence_pooled_fpr_delta']<=.01 and guards['full_recall_delta']>=-.01 and guards['recurrence_pooled_recall_delta']>=-.01 and wmean>=-.02)
    ref=json.loads(Path(a.reference).read_text()); fix=json.loads(Path(a.fixture).read_text()); iso=json.loads((root/'D_corr_branch/branch_isolation_audit.json').read_text()); caus=json.loads((root/'D_corr_branch/causality_audit.json').read_text()); ds=json.loads((root/'D_corr_branch/summary.json').read_text()); valid={'fixture_passed':bool(fix['passed']),'reference_consistency_passed':bool(ref['all_reference_checks_passed']),'D_off_exact_C':d_off,'classification_exact_copy':cls,'feature_tape_read_only':bool(iso['unchanged']),'no_gradient_to_C':not iso['C_gradient_path_present'],'causal_batches':bool(caus['all_update_batches_mature']),'no_terminal_training':int(caus['terminal_drain_training_steps'])==0,'branch_parameter_count_2401':int(ds['parameter_count'])==2401,'branch_really_updated':bool(ds['parameter_updated'])}; valid['all_pass']=all(valid.values()); joint=bool(online and recurrence and guards['all_pass'] and valid['all_pass']); diag=json.loads(Path(a.diagnostic).read_text()); local=bool(diag['summary']['local_capability_evidence_present'])
    label='joint_goal_signal' if joint else ('global_online_only' if online else ('recurrence_only' if recurrence else ('local_capability_only' if local else 'no_registered_gain')))
    hosts=[]
    for h in range(16):
        cm=binary_metrics(C['probability'][:,h],y[:,h]); dm=binary_metrics(D['probability'][:,h],y[:,h]); hosts.append({'host':h,'C':cm,'D_corr':dm,**diff(dm,cm)})
    blocks=[]
    for n,s,e in WINDOWS:
        for q in range(4):
            aa=s+q*32; bb=aa+32; cm=block(C['probability'],y,aa,bb); dm=block(D['probability'],y,aa,bb); blocks.append({'window':n,'block':q+1,'intervals':[aa,bb],'C':cm,'D_corr':dm,**diff(dm,cm)})
    delta=D['delta'].astype(np.float64); yy=y>0; corr={'quantiles':{str(q):float(np.quantile(delta,q)) for q in (0,.01,.1,.25,.5,.75,.9,.99,1)},'saturation_abs_gt_1p9_fraction':float((np.abs(delta)>1.9).mean()),'mean_delta_normal':float(delta[~yy].mean()),'mean_delta_positive':float(delta[yy].mean()),'mean_absolute_delta':float(np.abs(delta).mean())}
    comp={'protocol':'035','run_id':str(a.run_id),'development_only':True,'independent_confirmation':False,'C_full':fc,'D_corr_full':fd,'full_AP_delta':full,'windows':wins,'six_window_equal_weight_AP_delta':mean6,'positive_window_count':int(pos),'late4_equal_weight_AP_delta':late,'prefix32_equal_weight_AP_delta':first32,'prefix64_equal_weight_AP_delta':first64,'recurrence_pooled':{'C':pc,'D_corr':pd,**diff(pd,pc)},'W_blocks':wr,'guardrails':guards,'online_development_signal':online,'recurrence_development_signal':recurrence,'joint_goal_signal':joint,'result_label':label,'prior_033_strong_AP_reference_report_only':.03,'validity':valid,'per_host':hosts,'four_nonoverlap32_blocks':blocks,'correction_distribution':corr,'historical_diagnostic_summary':diag['summary']}; dump_json(out/'comparison.json',comp)
    cs=json.loads((root/'C_ref_035/summary.json').read_text()); cost={'C_path':cs['cost'],'correction_branch':ds['cost'],'deployment_cost_accounting':'D_corr total deployment includes the full continuously learning C path plus the correction branch; branch wall time alone is not total D cost','extra_trainable_parameters':2401,'classification_extra_parameters':0}; dump_json(out/'cost_profile.json',cost)
    status={'protocol':'035','run_id':str(a.run_id),'completed':True,'scientific_training_sequences_started':2,'scientific_training_sequences_completed':2,'sequence_names':['C_ref_035','D_corr_branch'],'new_simulator_streams':0,'extra_seeds':0,'hyperparameter_sweeps':0,'old_D_replays':0,'cache_diagnostic_suites':1,'additional_cache_router_trials':0,'automatic_followup_training':False,'result_label':label,'online_development_signal':online,'recurrence_development_signal':recurrence,'joint_goal_signal':joint,'validity_all_pass':valid['all_pass'],'stop_after_registered_budget':True,'development_only':True,'statistical_confirmation':False}; dump_json(out/'status.json',status)
    md=['# Protocol-035 Results','',f'Run: `{a.run_id}`. Development-only structural-component experiment; not independent statistical confirmation.','','## Registered result','',f'- Result label: **{label}**.',f'- Full-stream AP delta D_corr − C: **{full:+.6f}**.',f'- Six-recurrence equal-weight AP delta: **{mean6:+.6f}**; positive windows: **{pos}/6**.',f'- Late-four mean AP delta: **{late:+.6f}**.',f'- Global online signal: **{online}**; recurrence signal: **{recurrence}**; common guardrails: **{guards["all_pass"]}**; joint goal: **{joint}**.','','## Capability coverage diagnosis','',f'- Existing snapshot count: **{diag["snapshot_count"]}**.',f'- Supported predefined cells with hindsight local positive AP contrast: **{diag["summary"]["sufficient_cells_with_hindsight_local_positive_AP"]}**.','- These cells are hindsight diagnostics, not online routing results or independent seeds.','','## Isolation and causality','',f'- C reference reproduction passed: **{valid["reference_consistency_passed"]}**.',f'- D_off exactly equals C: **{d_off}**; classification exact copy: **{cls}**.',f'- Tape read-only/no gradient to C: **{valid["feature_tape_read_only"] and valid["no_gradient_to_C"]}**.',f'- Branch actually updated: **{valid["branch_really_updated"]}**; extra trainable parameters: **2401**.','','## Guardrails','',f'- Full FPR delta: **{guards["full_fpr_delta"]:+.6f}**; full recall delta: **{guards["full_recall_delta"]:+.6f}**.',f'- Pooled recurrence FPR delta: **{guards["recurrence_pooled_fpr_delta"]:+.6f}**; recall delta: **{guards["recurrence_pooled_recall_delta"]:+.6f}**.',f'- W-block equal-weight AP delta: **{wmean:+.6f}**.','','## Scope limits','', '- No claim is made for dynamic birth, protected memory, learned routing, hard deletion, equal-capacity superiority, or cross-seed generalization.','- The branch uses a distinct binary correction objective, so any gain cannot be attributed to topology alone.','- Exactly two new scientific training sequences were used; no new stream, extra seed, threshold sweep, old-D retraining, or automatic follow-up was run.','']; Path(a.docs_output).write_text('\n'.join(md)+'\n',encoding='utf8'); print(json.dumps(status,indent=2))
if __name__=='__main__': main()
