"""Protocol 021 — register the unseen regime (cascade_v1) before model work.

The registry is DERIVED from the generator module so that the registered
mechanism can never drift away from the implemented one: ``CASCADE_V1`` in
``simulator/workload/BitbrainWorkloadProtocol021.py`` is the single source of
truth, and this script records its hash alongside the mechanism.

Claim levels follow protocol §4 (U0..U4) and §8.5; they must be reported
separately, never collapsed into a single ``unseen=true``.

    U1 source-disjoint        : PASS   (evidence: exclusion_registry.json)
    U2 parameter-combo unseen : PASS   (the cascade envelope combination was
                                        never generated by the offline chain)
    U3 generator mechanism    : PASS   (evidence: exposure_ledger.json
                                        mechanism_exclusion = not_found)
    U4 distributional novelty : null   (filled by analyze_ftmoe_protocol021_unseen.py)

Usage:
    python register_ftmoe_protocol021_unseen.py
"""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT_DIR = ROOT / "artifacts/ftmoe_online/protocol_021"
REGISTRY = OUT_DIR / "unseen_registry/cascade_v1.json"
AUDIT_DIR = OUT_DIR / "offline_coverage_audit"
GENERATOR = ROOT / "simulator/workload/BitbrainWorkloadProtocol021.py"
PREPARE = ROOT / "prepare_ftmoe_protocol021_unseen.py"


def sha(path):
    value = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for block in iter(lambda: stream.read(4 * 1024 * 1024), b""):
            value.update(block)
    return value.hexdigest()


def canonical_sha(payload):
    """Hash of the payload without its own registry hash field."""
    body = {k: v for k, v in payload.items() if k != "registry_sha256"}
    return hashlib.sha256(
        json.dumps(body, ensure_ascii=False, sort_keys=True,
                   separators=(",", ":")).encode("utf8")).hexdigest()


def main():
    from simulator.workload.BitbrainWorkloadProtocol021 import (
        CASCADE_PROBABILITY_CANDIDATES, CASCADE_V1)

    ledger_path = AUDIT_DIR / "exposure_ledger.json"
    exclusion_path = AUDIT_DIR / "exclusion_registry.json"
    split_path = ROOT / "artifacts/ftmoe_online/protocol_020/vm_split.json"
    ledger = json.loads(ledger_path.read_text(encoding="utf8"))
    split = json.loads(split_path.read_text(encoding="utf8"))
    cohort_sizes = {name: len(ids) for name, ids in split["cohorts"].items()}

    mechanism = {k: v for k, v in CASCADE_V1.items()
                 if k != "forbidden_inputs"}
    registry = {
        "protocol": "021",
        "regime_id": CASCADE_V1["regime_id"],
        "registered_at": "2026-09-10",
        "registered_before_model_runs": True,
        "claim_level": {
            "U0_new_seed_or_replay": True,
            "U1_source_disjoint": True,
            "U2_parameter_combo_unseen": True,
            "U3_generator_mechanism_unseen": True,
            "U4_distributional_novelty": None,
            "U4_status": "pending analyze_ftmoe_protocol021_unseen.py",
        },
        "claim_level_notes": {
            "U0_U1_not_sufficient": "A new seed/replay and a disjoint VM cohort are not, by themselves, evidence of a new regime (protocol §4).",
            "U3_evidence": "offline_coverage_audit/exposure_ledger.json -> mechanism_exclusion.temporal_cpu_ram_disk_cascade: searched 1003 files of the 014/019/020 chain; cascade/cpu_to_ram/delayed/mechanism_seed/hysteresis/feedback = 0 matches.",
            "U1_evidence": "offline_coverage_audit/exclusion_registry.json -> used_vm_ids: pilot cohort p20_online (94 VMs) is disjoint from the P20 S6 train (277) and dev (86) cohorts; protocol §8.4 authorises the P20 online cohort subject to that disjointness.",
            "U1_limitation": "source-unseen relative to the full historical chain (P014 upstream VM selection is not registered anywhere) remains UNVERIFIED, per protocol §4.",
            "U2_note": "The registered envelope (burst 3-5 intervals at >= host CPU capacity from age 1; RAM target ramp at +4; capped self-cleaning retained disk term at +8) does not exist anywhere in the offline chain (see U3 evidence), so the parameter combination is unseen by construction.",
        },
        "mechanism": mechanism,
        "observable_history": CASCADE_V1["observable_history"],
        "forbidden_inputs": list(CASCADE_V1["forbidden_inputs"]),
        "development_only": True,
        "cascade_probability_candidates": list(CASCADE_PROBABILITY_CANDIDATES),
        "pilot_registration": {
            "cohort": "online",
            "cohort_source": "artifacts/ftmoe_online/protocol_020/vm_split.json cohorts.online",
            "cohort_size": cohort_sizes.get("online"),
            "cohort_sizes_all": cohort_sizes,
            "disjoint_from_s6_train": not (set(split["cohorts"]["online"])
                                           & set(split["cohorts"]["train"])),
            "disjoint_from_p20_dev": not (set(split["cohorts"]["online"])
                                          & set(split["cohorts"]["dev"])),
            "replay_seed": 600,
            "scored_intervals": 1200,
            "guard_intervals": 1,
            "familiar_environment": "Protocol-020 baseline phase (capacity scales 1.0/1.0/0.9, adapter ram_upper=1400)",
            "data_only": True,
        },
        "generator": {
            "path": "simulator/workload/BitbrainWorkloadProtocol021.py",
            "sha256": sha(GENERATOR),
        },
        "collector": {
            "path": "prepare_ftmoe_protocol021_unseen.py",
            "sha256": sha(PREPARE),
        },
        "audit_evidence": {
            "exposure_ledger": {
                "path": str(ledger_path.relative_to(ROOT)).replace("\\", "/"),
                "sha256": sha(ledger_path),
                "sources_audited": sum(len(stage.get("sources", []))
                                       for stage in ledger.get("learning_chain", [])),
            },
            "exclusion_registry": {
                "path": str(exclusion_path.relative_to(ROOT)).replace("\\", "/"),
                "sha256": sha(exclusion_path),
            },
        },
        "not_a_claim": [
            "The registry itself proves nothing about performance; it records what the data layer was allowed to be.",
            "U4 is null until the distributional audit runs; a generator difference alone is not distributional novelty.",
        ],
    }
    registry["registry_sha256"] = canonical_sha(registry)

    REGISTRY.parent.mkdir(parents=True, exist_ok=True)
    REGISTRY.write_text(json.dumps(registry, ensure_ascii=False, indent=2) + "\n",
                        encoding="utf8")
    print(json.dumps({"registered": str(REGISTRY),
                      "regime_id": registry["regime_id"],
                      "generator_sha256": registry["generator"]["sha256"],
                      "registry_sha256": registry["registry_sha256"],
                      "u3": registry["claim_level"]["U3_generator_mechanism_unseen"],
                      "u4": registry["claim_level"]["U4_distributional_novelty"]},
                     ensure_ascii=False))


if __name__ == "__main__":
    main()
